### ISSUE TITLE
How I can use this gem to start jruby server then sidekiq daemon running as same process

### ISSUE THREAD

**Issue by liuweijack** [mjonuschat/sidekiq-daemon#1]
Hi,Thanks for this gem .but how i use it?
How I can use this gem to start jruby server then sidekiq daemon running as the same process?

**Comment by mjonuschat** [comment]
Your use case isn't what the gem is about. This gem is used to start sidekiq with daemonization which means that you start it using `sidekiq-daemon` instead of `sidekiq` and it will automatically detach from the terminal and continue running in the background.
